version: '3.8'
services:
  reading_writing_data:
    build: ./reading_writing_data
    # Solo expose interno, no ports públicos
    expose:
      - "5000"
    env_file:
      - ./reading_writing_data/.env
    volumes:
      - ./reading_writing_data:/app
    networks:
      - social-network
    restart: unless-stopped

  video_publication:
    build: ./video_publication
    # Solo expose interno, no ports públicos  
    expose:
      - "5001"
    env_file:
      - ./video_publication/.env
    volumes:
      - ./video_publication:/app
    networks:
      - social-network
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP
      - '443:443'   # HTTPS  
      - '81:81'     # Panel admin
    volumes:
      - ./nginx-proxy-data:/data
      - ./nginx-proxy-letsencrypt:/etc/letsencrypt
    networks:
      - social-network
    depends_on:
      - reading_writing_data
      - video_publication

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - SUBDOMAINS=socialmanapp  # Tu subdominio real
      - TOKEN=tu-token-de-duckdns # Tu token real de DuckDNS
      - LOG_FILE=false
    volumes:
      - ./duckdns-config:/config
    restart: unless-stopped
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
