version: '3.8'

services:
  reading_writing_data:
    build: ./reading_writing_data
    ports:
      - "5000:5000"
    env_file:
      - ./reading_writing_data/.env
    volumes:
      - ./reading_writing_data:/app
    networks:
      - social-network

  video_publication:
    build: ./video_publication
    ports:
      - "5001:5001"
    env_file:
      - ./video_publication/.env
    volumes:
      - ./video_publication:/app
    networks:
      - social-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - reading_writing_data
      - video_publication
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
